# Generated by Django 3.2.13 on 2022-05-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل کاربر')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مجوز ورود به سایت؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین سایت؟')),
                ('is_author', models.BooleanField(default=False, verbose_name='نویسنده سایت؟')),
                ('email_activate', models.BooleanField(default=False, verbose_name=' ایا ایمیل فعال شده ؟')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('code', models.PositiveSmallIntegerField(verbose_name='کد اعتبار سنجی')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف',
                'verbose_name_plural': 'کد های یکبار مصرف',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=11, verbose_name='کد ملی')),
                ('bio', models.TextField(max_length=500, verbose_name='توضیحاتی درباره خود')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
