# Generated by Django 3.2.13 on 2022-05-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(choices=[('author', 'نویسندگی'), ('contact', 'تماس با ما')], max_length=7, verbose_name='موضوع')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت کاربر',
                'verbose_name_plural': 'تیکت کاربران',
            },
        ),
        migrations.CreateModel(
            name='AdminTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ticket', to='tickets.ticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت ادمین',
                'verbose_name_plural': 'پاسخ های تیکت ادمین',
            },
        ),
    ]
